### ISSUE TITLE
build fails on node v0.12.7 and node-gyp v2.0.1

### ISSUE THREAD

**Issue by balusamy** [anton-kotenko/kyotocabinet-node#4]
It was building successfully on v0.12.5.  After upgrading to v0.12.7, it failed.   

here is the build output:

shopping@f3:~/test$ npm install git+ssh://git@github.com:anton-kotenko/kyotocabinet-node.git
-
> kyotocabinet@0.2.0 install /home/shopping/test/node_modules/kyotocabinet
> node-gyp rebuild

make: Entering directory `/home/shopping/test/node_modules/kyotocabinet/build'
  CXX(target) Release/obj.target/kyotonode/src/main.o
In file included from ../src/cursor.h:54:0,
                 from ../src/export_to_v8.h:10,
                 from ../src/poly_db.h:5,
                 from ../src/main.cc:3:
../src/cursor.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE ExportCursor::JsConstructor(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/cursor.cc:17:12: error: ‘NanScope’ was not declared in this scope
   NanScope();
            ^
../src/cursor.cc:19:18: error: ‘args’ was not declared in this scope
   instance->Wrap(args.This()); 
                  ^
../src/cursor.cc:20:17: error: ‘NanReturnThis’ was not declared in this scope
   NanReturnThis();
                 ^
../src/cursor.cc: In static member function ‘static v8::Handle<v8::Function> ExportCursor::Init()’:
../src/cursor.cc:24:43: error: ‘NanNew’ was not declared in this scope
   v8::Local<v8::FunctionTemplate> f_tpl = NanNew<v8::FunctionTemplate>(ExportCursor::JsConstructor);
                                           ^
../src/cursor.cc:24:70: error: expected primary-expression before ‘>’ token
   v8::Local<v8::FunctionTemplate> f_tpl = NanNew<v8::FunctionTemplate>(ExportCursor::JsConstructor);
                                                                      ^
../src/cursor.cc:25:40: error: expected primary-expression before ‘>’ token
   f_tpl->SetClassName(NanNew<v8::String>("Cursor"));
                                        ^
../src/cursor.cc:27:60: error: invalid conversion from ‘Nan::NAN_METHOD_RETURN_TYPE (*)(Nan::NAN_METHOD_ARGS_TYPE) {aka void (*)(const Nan::FunctionCallbackInfo<v8::Value>&)}’ to ‘v8::FunctionCallback {aka void (*)(const v8::FunctionCallbackInfo<v8::Value>&)}’ [-fpermissive]
   NODE_SET_PROTOTYPE_METHOD(f_tpl, "set", ExportCursor::Set);
                                                            ^
In file included from ../node_modules/nan/nan.h:24:0,
                 from ../src/main.cc:1:
/home/shopping/.node-gyp/0.12.7/src/node.h:244:13: error:   initializing argument 3 of ‘void node::NODE_SET_PROTOTYPE_METHOD(v8::Handle<v8::FunctionTemplate>, const char*, v8::FunctionCallback)’ [-fpermissive]
 inline void NODE_SET_PROTOTYPE_METHOD(v8::Handle<v8::FunctionTemplate> recv,
             ^
In file included from ../src/cursor.h:54:0,
                 from ../src/export_to_v8.h:10,
                 from ../src/poly_db.h:5,
                 from ../src/main.cc:3:
../src/cursor.cc:28:66: error: invalid conversion from ‘Nan::NAN_METHOD_RETURN_TYPE (*)(Nan::NAN_METHOD_ARGS_TYPE) {aka void (*)(const Nan::FunctionCallbackInfo<v8::Value>&)}’ to ‘v8::FunctionCallback {aka void (*)(const v8::FunctionCallbackInfo<v8::Value>&)}’ [-fpermissive]
   NODE_SET_PROTOTYPE_METHOD(f_tpl, "remove", ExportCursor::Remove);
                                                                  ^
......

Thanks.

**Comment by anton-kotenko** [comment]
I'm planning to fix this at the weekend.

**Comment by anton-kotenko** [comment]
According to tests in travis https://travis-ci.org/anton-kotenko/kyotocabinet-node, issue is fixed.

**Comment by balusamy** [comment]
It builds successfully now.  Thanks.
